# punto-pymes-backend/docker-compose.yml

services:
  # --- Aplicación: API Gateway ---
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development # Usa la etapa 'development' del Dockerfile
    # Le dice al contenedor qué app específica correr
    command: npm run start:dev punto-pymes-backend
    env_file:
      - .env # Carga las variables de entorno
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}" # Puerto 3000
    volumes:
      - .:/usr/src/app # Sincroniza tu código local con el contenedor
      - /usr/src/app/node_modules # No sobrescribas los node_modules del contenedor
    depends_on:
      - postgres_db
      - mongo_db

  # --- Aplicación: Microservicio Auth ---
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    # Corre el servicio 'auth'
    command: npm run start:dev auth
    env_file:
      - .env
    ports:
      # Exponemos el puerto 3001 para la comunicación interna
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db
      - mongo_db
  # --- Aplicación: Microservicio Personal ---
  personal_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    command: npm run start:dev personal # <-- El comando que corre
    env_file:
      - .env
    ports:
      # Exponemos el nuevo puerto
      - "${PERSONAL_SERVICE_PORT}:${PERSONAL_SERVICE_PORT}" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db
      - mongo_db
  # --- Base de Datos PostgreSQL ---
  postgres_db:
    image: postgres:15-alpine
    container_name: puntopymes_postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Base de Datos MongoDB ---
  mongo_db:
    image: mongo:6.0
    container_name: puntopymes_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    ports:
      - "${DB_MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: